### ISSUE TITLE
Show Axure Hotspot Elements

### ISSUE THREAD

**Issue by LennartHennigs** [srm985/axure-redline-tool#23]
Currently Hotspots are "invisible" in the redline tool. They can be clicked if one knows where they are.
Please consider to add fill or outline color (similar to Axure's mask setting) to indicate their position.

**Comment by srm985** [comment]
@LennartHennigs, could you please provide an example?

**Comment by LennartHennigs** [comment]
![hotspots.png](https://s9.postimg.org/ybahe41hr/hotspots.png)

Axure on the left, redline tool on the right.
In Axure hotspots are greenish, in the redline tool you have to know where the hotspot is located. 
You don't see where hotspots might be on the page.

**Comment by srm985** [comment]
Ah yea, this is definitely a bug. I've never seen those before or never considered them so I didn't account for them. I will resolve this.

**Comment by srm985** [comment]
@LennartHennigs, I'm having trouble seeing the hotspots even when the tool is not loaded on the page. See the link below. There should be two hotspots on the page. Can you create an example where the hotspots are actually visible on the page? Do they actually work like that?

https://h8txh4.axshare.com/#g=1&p=hotspots

**Comment by LennartHennigs** [comment]
Hi,
yes, hotspots are "invisible". They are a bit like the old HTML IMG MAP tags. You can define clickable areas anywhere on your page.

Within Axure you can toggle its visibility at "Views > Masks > Mask Hot Spots".
Thus I was asking for a similar feature.

**Comment by srm985** [comment]
@LennartHennigs it's been a while but I was just reviewing this. Can you remind me, are hotspots different than the "interactive elements" toggled with the button show in this screenshot?

![hotspots](https://user-images.githubusercontent.com/18337507/55032376-bb95c700-4fde-11e9-900e-0b2a1c9f23f7.PNG)

**Comment by LennartHennigs** [comment]
Hey. They are similar. In the sense that they will be highlighted when „show interactive elements“ is activated.

**Comment by srm985** [comment]
Would this feature then perform some different functionality than that of AxShare's option to provide highlighting?
