### ISSUE TITLE
Keep annotations clickable

### ISSUE THREAD

**Issue by LennartHennigs** [srm985/axure-redline-tool#24]
Currently Axure's autogenerated annotations are visible but not clickable when the redline tool is enabled. 

Please keep them clickable so one can still access the annotation content. Alternatively, consider adding the content in the redline tool sidebar.

**Comment by LennartHennigs** [comment]
I see. Could you pull the annotation text from the associated element and put in the pullout tab instead?

**Comment by srm985** [comment]
I will investigate further. I can't remember if Axure stores the text in the HTML itself or as JavaScript variables. If it's in the markup, then I could theoretically grab it.

**Comment by srm985** [comment]
This issue has been resolved and will be released in V1.1.5
