### ISSUE TITLE
Move redline enable switch

### ISSUE THREAD

**Issue by LennartHennigs** [srm985/axure-redline-tool#25]
The redline toggle switch is not accessible when the user clicks on the canvas and not on an element.
Consider moving the toggle next to the zoom buttons to have it always accessible.

**Comment by srm985** [comment]
@LennartHennigs, the switch should be accessible by clicking on the "pullout" tab for the side panel. Once open, the user can enable or disable the tool. Is this the behavior you are experiencing?

**Comment by LennartHennigs** [comment]
Yes, it is. But when the pullout tab is closed, you need an extra click (open the tab) to access it.
Thus I'd the switch next to the zoom buttons in the top left. 

Here a quick mockup:

![mockup](https://s9.postimg.org/f13gusxjz/Bildschirmfoto_2018-03-21_um_16.09.22.png)
