### ISSUE TITLE
Interaction Styles

### ISSUE THREAD

**Issue by LennartHennigs** [srm985/axure-redline-tool#26]
Hi,
currently the define Interaction Styles are not displayed in the redline tool. Only the state defined as the initial state (active, seleted, disabled). 
Consider showing the information (even though this might be messy, since it is potential a lot of css style information)

**Comment by srm985** [comment]
@LennartHennigs, just to be clear - you'd like to be able to see those CSS attributes applied for states like hover, active, disabled, etc.?

**Comment by LennartHennigs** [comment]
No, not really. But an interaction style could impact most of the style information you have in the pullout tab. This I't put the style information in tabs, one for each defined different state: 

[![tabs](https://s9.postimg.org/s7swumbcf/Bildschirmfoto_2018-03-21_um_16.19.38.png)

**Comment by LennartHennigs** [comment]
Does [this one](https://s9.postimg.org/s7swumbcf/Bildschirmfoto_2018-03-21_um_16.19.38.png) work?

**Comment by srm985** [comment]
Working now. I like the idea of the tabbed layout. That's pretty cool indeed. I'll definitely work towards this. The one thing that is tricky is that I have to know in advance what CSS attributes to show. As you know, there are hundreds of possible attributes. I tried to extract the key ones. I can start with that list for the other states, but then I'll also need to come up with those only relevant to the specific state. It's a great feature though and I'll pursue it!

**Comment by srm985** [comment]
Feature implemented. 

https://grmvy0.axshare.com/#g=1&p=pseudo-class
