### ISSUE TITLE
Copy Links Broken

### ISSUE THREAD

**Issue by w00tsite** [srm985/axure-redline-tool#56]
This is by far the most incredible plugin I've seen for axure, bravo!

Wanted to let you know that when using the latest version, the click to copy URLs at the top copy the following in the latest Chrome version:

https://ABCDEF.axshare.com?redline=dev#g=1&p=page
https://ABCDEF.axshare.com?redline=business#g=1&p=page&fn=0

**Comment by w00tsite** [comment]
Yeah -- I masked it, but you can take this one for a spin: http://assets.digitalsolutionpartners.com/X74P5N/

The two links copy as such:
http://assets.digitalsolutionpartners.com?redline=businessX74P5N/#g=1&p=page_1&fn=0
http://assets.digitalsolutionpartners.com?redline=devX74P5N/#g=1&p=page_1

I can provide the source file as well. Tested on both with and with out the legacy CNAME.

**Comment by srm985** [comment]
Now I see what's going on. It seems it has to do with how the links are formed on private instances of AxShare. I'll work to resolve this, but I might need your help in testing - as I don't have a private instance running.

**Comment by w00tsite** [comment]
Would be happy to help. Just let me know what you need!

**Comment by srm985** [comment]
@w00tsite, this issue should now be resolved. The CDN will take a few hours to update if you're using @latest for the link. Otherwise, you can point at the version 2.0.6 instance or copy the code block directly. If it's not working still, please let me know!

**Comment by w00tsite** [comment]
It appears to be working the test link I provided above. Thanks again -- this tool will prove to be very valuable.
